// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using System;
using xyz.lsyyy.Verification.Data;

namespace xyz.lsyyy.Verification.Data.Migrations
{
	[DbContext(typeof(MyDbContext))]
    [Migration("20210216042112_devide_controller_action")]
    partial class devide_controller_action
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("zyx.lsyyy.Verification.Data.Action", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActionName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ControllerName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("zyx.lsyyy.Verification.Data.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid?>("SuperiorDepartmentId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SuperiorDepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("zyx.lsyyy.Verification.Data.DepartmentActionMap", b =>
                {
                    b.Property<Guid>("ActionTagId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.HasIndex("ActionTagId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("DepartmentActionMaps");
                });

            modelBuilder.Entity("zyx.lsyyy.Verification.Data.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("zyx.lsyyy.Verification.Data.PositionActionMap", b =>
                {
                    b.Property<Guid>("ActionTagId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("char(36)");

                    b.HasIndex("ActionTagId");

                    b.HasIndex("PositionId");

                    b.ToTable("PositionActionMaps");
                });

            modelBuilder.Entity("zyx.lsyyy.Verification.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("zyx.lsyyy.Verification.Data.UserActionMap", b =>
                {
                    b.Property<Guid>("ActionTagId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasIndex("ActionTagId");

                    b.HasIndex("UserId");

                    b.ToTable("UserActionMaps");
                });

            modelBuilder.Entity("zyx.lsyyy.Verification.Data.Department", b =>
                {
                    b.HasOne("zyx.lsyyy.Verification.Data.Department", "SuperiorDepartment")
                        .WithMany()
                        .HasForeignKey("SuperiorDepartmentId");
                });

            modelBuilder.Entity("zyx.lsyyy.Verification.Data.DepartmentActionMap", b =>
                {
                    b.HasOne("zyx.lsyyy.Verification.Data.Action", "Action")
                        .WithMany()
                        .HasForeignKey("ActionTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("zyx.lsyyy.Verification.Data.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("zyx.lsyyy.Verification.Data.Position", b =>
                {
                    b.HasOne("zyx.lsyyy.Verification.Data.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("zyx.lsyyy.Verification.Data.PositionActionMap", b =>
                {
                    b.HasOne("zyx.lsyyy.Verification.Data.Action", "Action")
                        .WithMany()
                        .HasForeignKey("ActionTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("zyx.lsyyy.Verification.Data.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("zyx.lsyyy.Verification.Data.User", b =>
                {
                    b.HasOne("zyx.lsyyy.Verification.Data.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("zyx.lsyyy.Verification.Data.UserActionMap", b =>
                {
                    b.HasOne("zyx.lsyyy.Verification.Data.Action", "Action")
                        .WithMany()
                        .HasForeignKey("ActionTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("zyx.lsyyy.Verification.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
